name: Pawn Compiler Online

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip Include Folder
        run: |
          if [ -f "include.zip" ]; then
            unzip include.zip
          fi

      - name: Compile Pawn Script
        uses: pawn-lang/compiler-action@v1
        with:
          entrypoint: 'modernhudrp.pwn'
          output: 'modernhudrp.amx'
          include: 'include'

      - name: Upload AMX Result
        uses: actions/upload-artifact@v4
        with:
          name: compiled-amx
          path: modernhudrp.amx
          
